version: 2

updates:
  - package-ecosystem: "npm"
    target-branch: "dependabot"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "fix"
      prefix-development: "ci"
      include: "scope"
    reviewers:
      - superflyxxi
    assignees:
      - superflyxxi
  - package-ecosystem: "docker"
    target-branch: "dependabot"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "fix"
      prefix-development: "ci"
      include: "scope"
    reviewers:
      - superflyxxi
    assignees:
      - superflyxxi
  - package-ecosystem: "docker"
    target-branch: "dependabot"
    directory: "/int-test"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ci"
      prefix-development: "ci"
      include: "scope"
    reviewers:
      - superflyxxi
    assignees:
      - superflyxxi
