version: 2

basic: &basic
  schedule:
    interval: "monthly"
  reviewers:
    - superflyxxi

updates:
  - package-ecosystem: "npm"
    <<: *basic
    directory: "/"
  - package-ecosystem: "docker"
    <<: *basic
    directory: "/"
  - package-ecosystem: "docker"
    <<: *basic
    directory: "/int-test"
