version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "dependencies"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "fix: "
      prefix-development: "fix(ci): "
    reviewers:
      - superflyxxi
  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "dependencies"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "fix: "
      prefix-development: "fix(ci): "
    reviewers:
      - superflyxxi
  - package-ecosystem: "docker"
    directory: "/int-test"
    target-branch: "dependencies"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "fix: "
      prefix-development: "fix(ci): "
    reviewers:
      - superflyxxi
