version: '3'

services:
  phone-compare:
    image: phone-compare:build
    restart: always
    environment:
      NODE_ENV: development
  phone-compare-ci-test:
    image: phone-compare:inttest
    depends_on:
      - phone-compare
    restart: "no"
    environment:
      BASE_URL: "http://phone-compare:3000"
