version: '3'

services:
  phone-compare:
    image: ${DOCKER_REGISTRY}/phone-compare:${PRIMARY_DOCKER_TAG}
    restart: always
    environment:
      NODE_ENV: development
  phone-compare-ci-test:
    image: ${DOCKER_REGISTRY}/phone-compare:inttest-${PRIMARY_DOCKER_TAG}
    depends_on:
      - phone-compare
    restart: "no"
    environment:
      BASE_URL: "http://phone-compare:3000"
